security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /admin/login_check
                login_path: /admin/login
            logout:
                path: /admin/logout
            anonymous:    true

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/logout, role: ROLE_ADMIN }
        - { path: ^/admin/users, role: ROLE_SUPER_ADMIN }        
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }