#hsp_admin_homepage:
#    #pattern:  /admin/{name}
#    pattern:  /admin{trailingSlash}
#    requirements: { trailingSlash: "[/]{0,1}" }
#    defaults: { _controller: "HSPAdminBundle:Default:index"}
    
hsp_admin_link:
  pattern: /
  defaults: {_controller: "HSPAdminBundle:Default:index"}

hsp_admin_user_handling:
  pattern: /user
  defaults: {_contorller: "HSPAdminBundle:Default:userHandling"}
  
## stuff added by fos user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }