hsp_admin_link:
  pattern: /
  defaults: {_controller: "HSPAdminBundle:Default:index"}

hsp_admin_user_handling:
  pattern: /users
  defaults: {_controller: "HSPAdminBundle:User:userHandling"}

hsp_admin_user_add:
  pattern: /users/add
  defaults: {_controller: "HSPAdminBundle:User:userAddEdit"}

#hsp_admin_user_edit:
#  pattern: /users/{username}/edit
#  defaults: {_controller: "HSPAdminBundle:User:userEditHandling"}

hsp_admin_user_delete_confirm:
  pattern: /users/{username}/deleteconfirm
  defaults: {_controller: "HSPAdminBundle:User:userDeleteConfirm"}

hsp_admin_user_delete:
  pattern: /users/{username}/delete
  defaults: {_controller: "HSPAdminBundle:User:userDelete"}

## stuff added by fos user
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /group
    
fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: "FOSUserBundle:Security:logout" }
    

hsp_admin_router_handling:
    pattern: /router
    defaults: {_controller: "HSPAdminBundle:Router:routerHandling"}

hsp_admin_router_add:
  pattern: /router/add
  defaults: {_controller: "HSPAdminBundle:Router:routerAddEdit"}

hsp_admin_router_edit:
  pattern: /router/edit/{routerid}
  defaults: {_controller: "HSPAdminBundle:Router:routerAddEdit"}

hsp_admin_router_delete:
  pattern: /router/delete/{routerid}
  defaults: {_controller: "HSPAdminBundle:Router:routerDelete"}

hsp_admin_leaselist:
  pattern: /leaselist
  defaults: {_controller: "HSPAdminBundle:Lease:leaseList"}

hsp_admin_lease_exports:
  pattern: /leaselist/exports
  defaults: {_controller: "HSPAdminBundle:Default:leaseExports"}