parameters:
#    hsp_admin.example.class: HSP\AdminBundle\Example

services:
#    hsp_admin.example:
#        class: %hsp_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
